### ISSUE TITLE
[BUG] Problem on registration step(Error in request)

### ISSUE THREAD

**Issue by Alkhimovmv** [AlexKay28/langflow#96] opened 2022-02-04 19:42 UTC
[BUG]  Problem on registration step(Error in request) issue

Current Behavior:
If you register a user with an email OR username that is already in the database, an error appears: 
` "message": "Server internal error. (psycopg2.IntegrityError) duplicate key value violates unique constraint \"authorized_users_email_key\"\nDETAIL:  Key (email)=(111) already exists.\n\n[SQL: INSERT INTO authorized_users (uuid, session_token, username, password, email, created_date) VALUES (%(uuid)s, %(session_token)s, %(username)s, %(password)s, %(email)s, %(created_date)s)]\n[parameters: {'uuid': UUID('669871f3-30cd-47c4-9a94-f324a4fc658c'), 'session_token': None, 'username': '1112313', 'password': '1111', 'email': '111', 'created_date': datetime.datetime(2022, 2, 4, 19, 34, 12, 955579)}]\n(Background on this error at: https://sqlalche.me/e/14/gkpj)"`

Expected Behavior:
There should be a message `Username <111> and/or email <111> already exist"`

Steps To Reproduce:
Try to register a user with an existing email or username.

Environment:
OS: Ubuntu 20.04
docker: 20.10.12
docker-compose: 1.21.0

**Comment by AlexKay28** [comment] 2022-02-06 07:45
@Alkhimovmv should I attach response code different from 200OK?

**Comment by AlexKay28** [comment] 2022-02-22 19:27
the problem is going to be resolved in #97

**Closed** 2022-03-03 18:26 UTC
Labels: bug, backend
